<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sortie;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends \Doctrine\ORM\EntityRepository
{
    public function sortiesDeMoinsDunMois()
    {
        $dateJour = new \DateTime();
        $dateJour->format('Y-m-d');

        $em = $this->getEntityManager();

        $queryBuilder = $em->createQueryBuilder();

        $queryBuilder->select('sortie')
            ->from(Sortie::class, 'sortie')
            ->where('sortie.dateDebutSortie >= :date_now')
            ->andWhere('sortie.dateDebutSortie > (:date_now - 90)');

        $query = $queryBuilder->getQuery();
        $query->setParameter('date_now', date('Y-m-d'));
        $sortiesDeMoinsDunMois = $query->getResult();
        return $sortiesDeMoinsDunMois;
    }
}
